sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tS6uuCDT8c3gXa6ZvsK
    access-key-secret: s6CRipSUf9NaqiJWGbqMe9tVHUMtuo
    bucket-name: 12bubu
  redis:
    host: 121.41.58.226
    port: 6379
